wandb:
  project_name: "Pendulum-Planner"    # Name of the project on wandb
  run_name: "True-Dynamics"           # Name of the run on wandb
  logging_wandb: True                 # Whether to log the training to wandb
cem:
  horizon: 20                       # Planning horizon
  num_iter: 10                      # Number of consecutive CEM update iterations        
  num_elites: 50
  num_samples: 500
train:
  seed: 0
  sample_batch_size: 256            # Batch size for sampling from the replay buffer
  buffer_size: 100000               # Size of the replay buffer
  num_model_updates: 300            # Number of training iterations
  num_rollout_steps: 200            # Number of steps to rollout the agent
  num_exploration_steps: 1000       # Number of steps to collect data for the replay buffer
  val_buffer_size: 0                # Size of the validation buffer
  val_batch_size: 0                 # Batch size for evaluating the model
  eval_episodes: 1                  # Number of episodes to evaluate the agent
  eval_frequency: 25                # Number of training iterations between evaluation
  diff_states: False                # Whether to use the difference between states as input  